export const ERRORS_UPDATE_LIST = 'ERRORS_UPDATE_LIST';
export const ERRORS_REQUEST_FAILED = 'ERRORS_REQUEST_FAILED';
export const ERRORS_REQUEST_LOADING = 'ERRORS_REQUEST_LOADING';
export const ERRORS_TOGGLE_CREATE_REDIRECT = 'ERRORS_TOGGLE_CREATE_REDIRECT';
