export const AUTH_INSTALL_URL = 'AUTH_INSTALL_URL';
export const AUTH_INSTALL_ERROR = 'AUTH_INSTALL_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_DATA = 'AUTH_DATA';
