export const REDIRECT_REQUEST_LOADING = 'REDIRECT_REQUEST_LOADING';
export const REDIRECT_REQUEST_ERROR = 'REDIRECT_REQUEST_ERROR';
export const REDIRECT_REQUEST_FINISHED = 'REDIRECT_REQUEST_FINISHED';
export const REDIRECT_TOGGLE_ERROR_MESSAGE = 'REDIRECT_TOGGLE_ERROR_MESSAGE';
export const REDIRECT_REMOVE = 'REDIRECT_REMOVE';
export const REDIRECT_UPDATE = 'REDIRECT_UPDATE';
export const REDIRECT_CREATE = 'REDIRECT_CREATE';
export const REDIRECT_UPDATE_NEW_ITEM = 'REDIRECT_UPDATE_NEW_ITEM';
